build_ami:
  base_ami_product: com.ubuntu.cloud:server:18.04:amd64
  rootfs_skel_dirs:
    $append: rootfs.skel
  packages:
    $remove: docker.io
    $extend:
      - jenkins
      - openjdk-8-jre-headless
  cloud_config_data:
    apt_sources:
      - source: "deb https://pkg.jenkins.io/debian-stable binary/"
        filename: jenkins.list
        keyid: E12A9B7D32F2D50582E6
